/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package peliculas;

/**
 *
 * @author wong
 */
import peliculas.vistas.*;
public class peliculas extends javax.swing.JFrame {

    /**
     * Creates new form peliculas
     */
    public peliculas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        MenuPelicula = new javax.swing.JMenu();
        menuPeliculaCrear = new javax.swing.JMenuItem();
        Consultar = new javax.swing.JMenuItem();
        MenuActor = new javax.swing.JMenu();
        menuActorConsultar = new javax.swing.JMenuItem();
        menuActorCrear = new javax.swing.JMenuItem();
        MenuDirector = new javax.swing.JMenu();
        menuDirectorCrear = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MenuPelicula.setText("pelicula");

        menuPeliculaCrear.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        menuPeliculaCrear.setText("Crear");
        menuPeliculaCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPeliculaCrearActionPerformed(evt);
            }
        });
        MenuPelicula.add(menuPeliculaCrear);

        Consultar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        Consultar.setText("Consultar");
        Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarActionPerformed(evt);
            }
        });
        MenuPelicula.add(Consultar);

        jMenuBar1.add(MenuPelicula);

        MenuActor.setText("actor");

        menuActorConsultar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        menuActorConsultar.setText("consultar");
        menuActorConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActorConsultarActionPerformed(evt);
            }
        });
        MenuActor.add(menuActorConsultar);

        menuActorCrear.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        menuActorCrear.setText("crear");
        menuActorCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActorCrearActionPerformed(evt);
            }
        });
        MenuActor.add(menuActorCrear);

        jMenuBar1.add(MenuActor);

        MenuDirector.setText("Director");
        MenuDirector.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuDirectorMouseClicked(evt);
            }
        });

        menuDirectorCrear.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Y, java.awt.event.InputEvent.CTRL_MASK));
        menuDirectorCrear.setText("crear");
        menuDirectorCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDirectorCrearActionPerformed(evt);
            }
        });
        MenuDirector.add(menuDirectorCrear);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("consultar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        MenuDirector.add(jMenuItem1);

        jMenuBar1.add(MenuDirector);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 584, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 342, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuDirectorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuDirectorMouseClicked
        
    }//GEN-LAST:event_MenuDirectorMouseClicked

    private void menuActorConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActorConsultarActionPerformed
        consultarActor actor = new consultarActor();
        actor.setVisible(true);
    }//GEN-LAST:event_menuActorConsultarActionPerformed

    private void menuActorCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActorCrearActionPerformed
        agregarActor actor = new agregarActor();
        actor.setVisible(true);
    }//GEN-LAST:event_menuActorCrearActionPerformed

    private void menuDirectorCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDirectorCrearActionPerformed
        agregarDirector crearDirector = new agregarDirector();
        crearDirector.setVisible(true);
    }//GEN-LAST:event_menuDirectorCrearActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        consultarDirector director = new consultarDirector();
        director.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void menuPeliculaCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPeliculaCrearActionPerformed
        agregarPelicula pelicula = new agregarPelicula();
        pelicula.setVisible(true);
    }//GEN-LAST:event_menuPeliculaCrearActionPerformed

    private void ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarActionPerformed
        consultarPelicula pelicula = new consultarPelicula();
        pelicula.setVisible(true);
    }//GEN-LAST:event_ConsultarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            /*for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                   */
            javax.swing.UIManager.setLookAndFeel("com.birosoft.liquid.LiquidLookAndFeel");
            /*        break;
                }
            }*/
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(peliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(peliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(peliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(peliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new peliculas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Consultar;
    private javax.swing.JMenu MenuActor;
    private javax.swing.JMenu MenuDirector;
    private javax.swing.JMenu MenuPelicula;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem menuActorConsultar;
    private javax.swing.JMenuItem menuActorCrear;
    private javax.swing.JMenuItem menuDirectorCrear;
    private javax.swing.JMenuItem menuPeliculaCrear;
    // End of variables declaration//GEN-END:variables
}
